# Generated by Django 5.2.9 on 2026-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
