# Generated by Django 5.2.9 on 2026-01-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0005_remove_post_author_post_muallif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='muallif',
            new_name='author',
        ),
    ]
