# Generated by Django 5.2.9 on 2026-01-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0006_rename_muallif_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video faylni shu yerga yuklang (.mp4)', null=True, upload_to='news_videos/'),
        ),
    ]
